"use client"

import * as React from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Calendar } from "@/components/ui/calendar"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { CalendarIcon, Download, Share2, Sparkles, Youtube } from "lucide-react"
import { format } from "date-fns"
import { cn } from "@/lib/utils"
import { VideoPreview } from "@/components/video-preview"
import { Film } from "lucide-react" // Declared Film variable here

export function VideoCreationStudio() {
  const [stock1, setStock1] = React.useState("NFLX")
  const [stock2, setStock2] = React.useState("DIS")
  const [startDate, setStartDate] = React.useState<Date>(new Date("2023-06-01"))
  const [endDate, setEndDate] = React.useState<Date>(new Date("2024-12-31"))
  const [timeline, setTimeline] = React.useState("weekly")
  const [investment, setInvestment] = React.useState("500")
  const [duration, setDuration] = React.useState("10")
  const [showPreview, setShowPreview] = React.useState(false)
  const [isLoadingAI, setIsLoadingAI] = React.useState(false)
  const [isLoading, setIsLoading] = React.useState(false)
  const [videoUrl, setVideoUrl] = React.useState<string | null>(null)
  const [error, setError] = React.useState<string | null>(null)
  const [isYoutubeUploading, setIsYoutubeUploading] = React.useState(false)
  const [youtubeAuthUrl, setYoutubeAuthUrl] = React.useState<string | null>(null)
  const [youtubeSuccess, setYoutubeSuccess] = React.useState<string | null>(null)

  const handleGenerate = async () => {
    if (!stock1 || !stock2 || !startDate || !endDate) {
      setError("Please fill in all required fields")
      return
    }

    setIsLoading(true)
    setError(null)
    setVideoUrl(null)

    try {
      const payload = {
        stock1: stock1.toUpperCase(),
        stock2: stock2.toUpperCase(),
        start_date: format(startDate, "yyyy-MM-dd"),
        end_date: format(endDate, "yyyy-MM-dd"),
        daily_freq: timeline,
        "one-time-investment": parseInt(investment),
        vid_duration: parseInt(duration)
      }

      const response = await fetch("http://127.0.0.1:5000/stock_req", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      })

      const data = await response.json()

      if (data.status === "success") {
        setVideoUrl(data.video_url)
        setShowPreview(true)
      } else {
        setError(data.message || "Failed to generate video")
      }
    } catch (err) {
      setError("Failed to connect to the API. Make sure the server is running.")
      console.error("API Error:", err)
    } finally {
      setIsLoading(false)
    }
  }

  const handleYoutubeUpload = async () => {
    if (!videoUrl) {
      setError("No video available to upload")
      return
    }

    setIsYoutubeUploading(true)
    setError(null)
    setYoutubeSuccess(null)

    try {
      // First, get the YouTube auth URL
      const authResponse = await fetch("http://127.0.0.1:5000/youtube_auth", {
        method: "GET",
      })

      if (!authResponse.ok) {
        throw new Error("Failed to get YouTube auth URL")
      }

      const authData = await authResponse.json()
      
      if (authData.auth_url) {
        // Open YouTube OAuth in a popup window
        const popup = window.open(
          authData.auth_url,
          'youtube-auth',
          'width=600,height=600,scrollbars=yes,resizable=yes'
        )

        // Listen for the popup to close
        const checkClosed = setInterval(async () => {
          if (popup?.closed) {
            clearInterval(checkClosed)
            
            // Wait a moment for the callback to process
            setTimeout(async () => {
              try {
                // Now attempt to upload the video
                const uploadResponse = await fetch("http://127.0.0.1:5000/youtube_upload", {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                  },
                  body: JSON.stringify({
                    video_url: videoUrl,
                    title: `${stock1} vs ${stock2} Stock Comparison`,
                    description: `Stock comparison video between ${stock1} and ${stock2} from ${format(startDate, "MMM dd, yyyy")} to ${format(endDate, "MMM dd, yyyy")}. Generated by StockTube.`
                  }),
                })

                const uploadData = await uploadResponse.json()

                if (uploadData.status === "success") {
                  // Show success message
                  setError(null)
                  setYoutubeSuccess(`Video uploaded successfully! YouTube URL: ${uploadData.youtube_url}`)
                  // Clear success message after 10 seconds
                  setTimeout(() => setYoutubeSuccess(null), 10000)
                } else {
                  setError(uploadData.message || "Failed to upload to YouTube")
                }
              } catch (uploadErr) {
                setError("Failed to upload video to YouTube")
                console.error("Upload Error:", uploadErr)
              } finally {
                setIsYoutubeUploading(false)
              }
            }, 2000)
          }
        }, 1000)
      } else {
        throw new Error("No auth URL received")
      }
    } catch (err) {
      setError("Failed to initiate YouTube upload. Make sure the server is running.")
      console.error("YouTube Upload Error:", err)
      setIsYoutubeUploading(false)
    }
  }

  const handleAISuggestions = () => {
    setIsLoadingAI(true)
    
    // Simulate loading for better UX
    setTimeout(() => {
      // Curated list of trending stock comparisons with optimal settings
      const trendingComparisons = [
        {
          stock1: "NVDA",
          stock2: "AMD", 
          timeline: "daily",
          investment: "2500",
          duration: "45",
          template: "subway",
          reasoning: "AI chip rivalry - NVIDIA vs AMD battle for AI dominance"
        },
        {
          stock1: "AAPL",
          stock2: "MSFT",
          timeline: "weekly", 
          investment: "5000",
          duration: "60",
          template: "minecraft",
          reasoning: "Tech giants showdown - Apple vs Microsoft market cap race"
        },
        {
          stock1: "TSLA",
          stock2: "RIVN",
          timeline: "daily",
          investment: "1500",
          duration: "30", 
          template: "subway",
          reasoning: "EV revolution - Tesla vs Rivian electric future battle"
        },
        {
          stock1: "META",
          stock2: "GOOGL",
          timeline: "daily",
          investment: "3000", 
          duration: "45",
          template: "minecraft",
          reasoning: "Social media vs search - Meta's metaverse vs Google's AI"
        },
        {
          stock1: "AMZN",
          stock2: "NFLX",
          timeline: "weekly",
          investment: "2000",
          duration: "30",
          template: "subway", 
          reasoning: "Streaming wars - Amazon Prime vs Netflix content battle"
        },
        {
          stock1: "COIN",
          stock2: "HOOD",
          timeline: "daily",
          investment: "1000",
          duration: "15",
          template: "subway",
          reasoning: "Trading platforms - Coinbase vs Robinhood retail trading"
        },
        {
          stock1: "DIS",
          stock2: "NFLX", 
          timeline: "monthly",
          investment: "4000",
          duration: "60",
          template: "minecraft",
          reasoning: "Entertainment empire - Disney+ vs Netflix streaming dominance"
        },
        {
          stock1: "PLTR",
          stock2: "SNOW",
          timeline: "daily", 
          investment: "1200",
          duration: "30",
          template: "subway",
          reasoning: "Data analytics war - Palantir vs Snowflake big data race"
        }
      ]
      
      // Randomly select one of the trending comparisons
      const selectedComparison = trendingComparisons[Math.floor(Math.random() * trendingComparisons.length)]
      
      // Auto-fill ALL form fields
      setStock1(selectedComparison.stock1)
      setStock2(selectedComparison.stock2) 
      setTimeline(selectedComparison.timeline)
      setInvestment(selectedComparison.investment)
      setDuration(selectedComparison.duration)
      setTemplate(selectedComparison.template)
      
      // Set smart date ranges based on timeline
      const endDate = new Date()
      const startDate = new Date()
      
      if (selectedComparison.timeline === "daily") {
        // Last 3 months for daily data
        startDate.setMonth(startDate.getMonth() - 3)
      } else if (selectedComparison.timeline === "weekly") {
        // Last 6 months for weekly data  
        startDate.setMonth(startDate.getMonth() - 6)
      } else {
        // Last 12 months for monthly data
        startDate.setMonth(startDate.getMonth() - 12)
      }
      
      setStartDate(startDate)
      setEndDate(endDate)
      
      // Log the suggestion reasoning
      console.log("🎯 Smart Suggestion:", selectedComparison.reasoning)
      
      setIsLoadingAI(false)
    }, 800) // Simulate realistic loading time
  }

  return (
    <div className="grid gap-6 lg:grid-cols-2">
      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle className="gradient-text">Stock Selection</CardTitle>
            <CardDescription>Choose two stocks to compare</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="stock1">Stock 1</Label>
                <Input
                  id="stock1"
                  placeholder="e.g., MSFT"
                  value={stock1}
                  onChange={(e) => setStock1(e.target.value.toUpperCase())}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="stock2">Stock 2</Label>
                <Input
                  id="stock2"
                  placeholder="e.g., GOOG"
                  value={stock2}
                  onChange={(e) => setStock2(e.target.value.toUpperCase())}
                />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="gradient-text">Timeline Settings</CardTitle>
            <CardDescription>Configure the date range and frequency</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label>Start Date</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button
                      variant="outline"
                      className={cn(
                        "w-full justify-start text-left font-normal",
                        !startDate && "text-muted-foreground",
                      )}
                    >
                      <CalendarIcon className="mr-2 h-4 w-4" />
                      {startDate ? format(startDate, "PPP") : "Pick a date"}
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-auto p-0">
                    <Calendar mode="single" selected={startDate} onSelect={setStartDate} initialFocus />
                  </PopoverContent>
                </Popover>
              </div>
              <div className="space-y-2">
                <Label>End Date</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button
                      variant="outline"
                      className={cn("w-full justify-start text-left font-normal", !endDate && "text-muted-foreground")}
                    >
                      <CalendarIcon className="mr-2 h-4 w-4" />
                      {endDate ? format(endDate, "PPP") : "Pick a date"}
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-auto p-0">
                    <Calendar mode="single" selected={endDate} onSelect={setEndDate} initialFocus />
                  </PopoverContent>
                </Popover>
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="timeline">Data Frequency</Label>
              <Select value={timeline} onValueChange={setTimeline}>
                <SelectTrigger id="timeline">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="daily">Daily</SelectItem>
                  <SelectItem value="weekly">Weekly</SelectItem>
                  <SelectItem value="monthly">Monthly</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="investment">One-Time Investment ($)</Label>
              <Input id="investment" type="number" value={investment} onChange={(e) => setInvestment(e.target.value)} />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="gradient-text">Video Settings</CardTitle>
            <CardDescription>Customize your video output</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="duration">Video Duration (seconds)</Label>
              <Select value={duration} onValueChange={setDuration}>
                <SelectTrigger id="duration">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="10">10 seconds</SelectItem>
                  <SelectItem value="15">15 seconds</SelectItem>
                  <SelectItem value="30">30 seconds</SelectItem>
                  <SelectItem value="45">45 seconds</SelectItem>
                  <SelectItem value="60">60 seconds</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button 
              variant="outline" 
              className="w-full bg-transparent mb-3" 
              onClick={handleAISuggestions}
              disabled={isLoadingAI}
            >
              <Sparkles className="mr-2 h-4 w-4" />
              {isLoadingAI ? "Getting Smart Suggestions..." : "Get Smart Suggestions"}
            </Button>
            <Button 
              className="w-full" 
              size="lg" 
              onClick={handleGenerate}
              disabled={isLoading}
            >
              {isLoading ? "Generating Video..." : "Generate Video"}
            </Button>
            {error && (
              <div className="text-sm text-red-500 bg-red-50 p-3 rounded-md">
                {error}
              </div>
            )}
            {youtubeSuccess && (
              <div className="text-sm text-green-600 bg-green-50 p-3 rounded-md">
                {youtubeSuccess}
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      <div className="space-y-6">
        {isLoading ? (
          <Card className="flex h-[600px] items-center justify-center">
            <CardContent className="text-center">
              <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-primary mx-auto"></div>
              <p className="mt-4 text-lg font-medium">Loading...</p>
              <p className="text-sm text-muted-foreground">Generating your video, please wait</p>
            </CardContent>
          </Card>
        ) : showPreview && videoUrl ? (
          <>
            <Card className="overflow-hidden">
              <CardContent className="p-0">
                <div className="relative aspect-[9/16] bg-black">
                  <video 
                    src={videoUrl} 
                    controls 
                    className="w-full h-full object-cover"
                    poster=""
                  >
                    Your browser does not support the video tag.
                  </video>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle className="gradient-text">Export Options</CardTitle>
                <CardDescription>Download or share your video</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid gap-3">
                  <Button 
                    className="w-full bg-transparent" 
                    variant="outline"
                    onClick={() => window.open(videoUrl, '_blank')}
                  >
                    <Download className="mr-2 h-4 w-4" />
                    Download Video
                  </Button>
                  <Button 
                    className="w-full bg-red-600 hover:bg-red-700 text-white" 
                    onClick={handleYoutubeUpload}
                    disabled={isYoutubeUploading}
                  >
                    <Youtube className="mr-2 h-4 w-4" />
                    {isYoutubeUploading ? "Uploading to YouTube..." : "Upload to YouTube"}
                  </Button>
                  <div className="grid gap-2 sm:grid-cols-2">
                    <Button variant="outline" size="sm">
                      <Share2 className="mr-2 h-4 w-4" />
                      TikTok (9:16)
                    </Button>
                    <Button variant="outline" size="sm">
                      <Share2 className="mr-2 h-4 w-4" />
                      Instagram (9:16)
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </>
        ) : (
          <Card className="flex h-[600px] items-center justify-center">
            <CardContent className="text-center">
              <Film className="mx-auto h-16 w-16 text-muted-foreground" />
              <p className="mt-4 text-lg font-medium">No video generated yet</p>
              <p className="text-sm text-muted-foreground">Fill in the settings and click Generate Video</p>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  )
}
